### ISSUE TITLE
Add Appcelerator Titanium

### ISSUE THREAD

**Issue by FokkeZB** [harrycheung/Mobile-App-Performance#1]
Can I help you to add [Appcelerator](http://www.appcelerator.com) Titanium?

**Comment by harrycheung** [comment]
Of course. I downloaded it today, and took a stab at it, and I'm already running into something. Would you mind taking a look? It's under the Titanium directory.

**Comment by FokkeZB** [comment]
I've done some fixes to make the app work, but I don't know how exactly your test itself is supposed to work. Please give it a try now and let me know if I can help.

**Comment by harrycheung** [comment]
Perfect. Thanks for the patch. I just needed to understand how code was imported. I'll finish the port and get the results up.

**Comment by harrycheung** [comment]
@FokkeZB I decided to structure my js a little differently, but I'm worried there's a performance impact. I ported my all of my logic to JS and set it up so I can run in a browser. As a result, I didn't use the CommonJS module structure. I then put the JS logic in the <code>assets</code> folder, and used <code>Ti.include</code> to bring it into the Titanium app. Is this ok or am I going to experience a performance impact vs using <code>require</code>?

**Comment by harrycheung** [comment]
Btw, it's checked in right now if you want to take a look.

**Comment by FokkeZB** [comment]
I've made all JS libs CommonJS compatible so they can be used in both the JS test and the Titanium test. I also took running the actual test and reading the multi data out of `run.js` so this file can be shared as well. See #3

**Comment by harrycheung** [comment]
Thanks for the patch. However, I'm still seeing the same performance as before. It's taking about 5.5 seconds to run the 1000 iteration loop (all the other apps do it at around 1 second). I'm seeing if there's an optimization flag I need to set in Titanium to speed things up, but I'm not being successful.

**Comment by FokkeZB** [comment]
What are you running it on? I get that 1s.

**Comment by harrycheung** [comment]
iPhone 6/8.1.2

**Comment by FokkeZB** [comment]
Mmm, wait... was running in iOS Simulator.

Getting 5.3s on an iPhone 6 as well.

But then, running the JS version on http://dev.fokkezb.nl/benchmark in Safari on the same phone also gets me no lower then 3s.

Are you sure the tests on the others are identical?

**Comment by harrycheung** [comment]
Yeah, the code isn't that complicated, and I verified it with unit tests in
JavaScript/test.html. Btw, I get the same 3s in Safari.

**Comment by FokkeZB** [comment]
So what your benchmarks really are comparing is the efficiency of different languages, including different bytecode compilations.

**Comment by harrycheung** [comment]
Yup. Out of curiosity, what did you think I was measuring?

**Comment by FokkeZB** [comment]
Good one.. I guess I was mislead by the "Mobile **App** Performance" title ;)

What would be more interesting then is to test Appcelerator's new Hyperloop Abstraction Layer. This new JS2Native compiler will replace the current interpreter.

Hyperloop is currently only available through the Windows Phone SDK developer preview:
http://www.tidev.io/2015/01/12/how-to-try-the-titanium-windows-platform-preview-for-free/

I will try to port the test to it.

**Comment by harrycheung** [comment]
Ah, yeah. Sorry for the misunderstanding. It was a trade off of the short
title vs writing a super long descriptive one.  Have an idea when the
JS2Native compiler will be available for iOS or Android? Hard for me to
compare results otherwise.

On Sat, Feb 21, 2015 at 10:39 AM, Fokke Zandbergen <notifications@github.com

**Comment by FokkeZB** [comment]
The Windows Phone SDK based on Hyperloop is not feature complete yet and the tests fail to work.

The iOS/Android version is only available in previous iteration of hyperloop:

- https://github.com/appcelerator/hyperloop (~ 4th gen)
- https://github.com/appcelerator/hyperloop-cli (~ 5th gen)

We'll have to wait for Windows to be stable and/or iOS/Android to be finished later this year.
