### ISSUE TITLE
Missing fall-through in JavaScript version of the session manager?

### ISSUE THREAD

**Issue by kasperl** [harrycheung/Mobile-App-Performance#17]
Should this break be removed?
https://github.com/harrycheung/Mobile-App-Performance/blob/master/JavaScript/session_manager.js#L73

**Comment by harrycheung** [comment]
No. A lap may have different start and end gates. If a lap has the same
start/finish gate then, it would be of type START_FINISH. Make sense?

**Comment by kasperl** [comment]
I'm just surprised by the difference to, say, the Java version:

https://github.com/harrycheung/Mobile-App-Performance/blob/master/Shared/Java/harrycheung/map/shared/SessionManager.java#L69

and the Swift variant:

https://github.com/harrycheung/Mobile-App-Performance/blob/master/SwiftApp/SwiftApp/SessionManager.swift#L77

that both seems to fall-through from the START_FINISH and FINISH cases to the START case.

**Comment by kasperl** [comment]
FWIW, the C++ version also falls through from START_FINISH and FINISH cases to the START case:

https://github.com/harrycheung/Mobile-App-Performance/blob/master/Shared/CPP/HCMSessionManager.cpp#L63

**Comment by harrycheung** [comment]
You're absolutely right. Good catch. Looks like a regression that was
introduced with FokkeZB's PR #11. I'll revert.
