### ISSUE TITLE
Xamarin Forms

### ISSUE THREAD

**Issue by 3green** [harrycheung/Mobile-App-Performance#4]
Hi nice metrics, though it would be useful if Xamarin Classic and Forms could both be seen side by side?

**Comment by harrycheung** [comment]
My apps don't test UI performance. However, having said that, can you
provide an example of what you would want tested?

**Comment by 3green** [comment]
OK, re example, if it exists, then some standard UI benchmarking code that could be used across all platforms would be useful. Failing that, here is some code being used for Xamarin Foms performance testing : http://stackoverflow.com/questions/26364509/why-is-xamarin-forms-so-slow-when-displaying-a-few-labels-especially-on-android that might be suitable? I am not a performance specialist, so whilst it would be useful to see our code benchmarked it might not be as useful for the community?

**Comment by harrycheung** [comment]
Yeah, since this seems like a specific issue, I don't know if I'll get
around to it. It's also not clear that UI performance for one case will be
exemplary of another case. Even my computational test case doesn't
unequivocally state that one tool is better than another.
