### ISSUE TITLE
datetime.utcnow

### ISSUE THREAD

**Issue by ChaseFlorell** [harrycheung/Mobile-App-Performance#6]
I'm actually just interested in your helper method. In your article you said that UTC now is very expensive / slow. what makes your helper method faster? I'm intrigued.

**Comment by harrycheung** [comment]
The helper is never used in my performance test (I should take it out), but
it's used in my actual app. The helper isn't faster at all. I need time
based on the epoch which is why i need the helper.

**Comment by ChaseFlorell** [comment]
ah, gotcha.
